---
triple:          'arm64-apple-darwin'
binary-path:     service
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _checkError, symObjAddr: 0x0, symBinAddr: 0x100003C08, symSize: 0x84 }
  - { offsetInCU: 0x7B, offset: 0x7B, size: 0x8, addend: 0x0, symName: _checkError, symObjAddr: 0x0, symBinAddr: 0x100003C08, symSize: 0x84 }
  - { offsetInCU: 0xAD, offset: 0xAD, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x84, symBinAddr: 0x100003C8C, symSize: 0x1E8 }
  - { offsetInCU: 0x169, offset: 0x169, size: 0x8, addend: 0x0, symName: __OSSwapInt16, symObjAddr: 0x26C, symBinAddr: 0x100003E74, symSize: 0x24 }
...
